<?php

namespace ThinkBack\MediaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MediaResourceListingsCacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaResourceListingsCacheRepository extends EntityRepository
{
    /*
     * gets cached listings based on search parameters and api type as well as timeStamp on record
     * records older than 24 hours must be removed
     * @params includes mediatype, optional decade, optional genre, optional keywords,
     * optional page
     */
    public function getCachedListings(array $params, $apiName){
  
        //initial selection parameters
        $q = $this->createQueryBuilder('cl')
                ->select('cl.xmlData')
                ->innerJoin('cl.mediaType', 'm')
                ->innerJoin('cl.api', 'a')
                ->where('m.slug = :mediaSlug')
                ->andWhere('a.apiName = :apiName')
                ->setParameters(array(
                    'mediaSlug'     =>  $params['media'],
                    'apiName'       =>  $apiName,
                   ));
                //->getQuery();*/
        
        if($decade != Decade::$default){
            //$q = $this->addDecadeQueryPart($params['decade'], $q);
            $q .= innerJoin('cl.decade', 'd')
                ->where('d.decadeName = :decadeName')
                ->setParameter('decadeName', $decade);
        }
                
        try{
            $q = $q->getQuery;
            return $q->getSingleResult();
        }catch(\Doctrine\ORM\NoResultException $ex){
            return null;
        }
     }
     
     
}