<?php
/**
 * APIRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

namespace SkNd\MediaBundle\Repository;

use Doctrine\ORM\EntityRepository;

class APIRepository extends EntityRepository
{
    public function getAPIByName($name){
        return $this->findOneBy(array('name' => $name));
    }
    
}