<?php

namespace SkNd\MediaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * APIRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class APIRepository extends EntityRepository
{
    public function getAPIByName($apiName){
        return $this->findOneBy(array('apiName' => $apiName));
    }
    
    /*public function getDefaultAPIName(){
        return $this->createQueryBuilder('a')
                ->select('a.apiName')
                ->where('id = :id')
                ->setParameter('id', 1)
                ->getQuery()
                ->getResult();
    }*/
    

}