imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    
framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    #secure_controllers:  true
    secure_all_services: false

fos_user:
  db_driver: orm
  firewall_name: main
  user_class: ThinkBack\UserBundle\Entity\User
  registration:
    form:
      type: ThinkBack_user_registration
      
stof_doctrine_extensions:
  orm:
    default:
      sluggable: true

think_back_media:
  amazonapi:
    access_params:
      amazon_public_key: %amazon_public_key%
      amazon_private_key: %amazon_uk_private_key%
      amazon_associate_tag: %amazon_associate_tag%
    #this can be set in the config but has a default value defined in the Configuration.php of the bundle
    #amazon_signed_request:
    #  class: ThinkBack\MediaBundle\MediaAPI\DummyAmazonSignedRequest
  youtubeapi: ~
    #use the below parameter to inject a dummy class for testing
    #youtube_request_object: ThinkBack\MediaBundle\MediaAPI\DummyYouTubeRequestObject
     
    


#jms_aop:
#    cache_dir: %kernel.cache_dir%/jms_aop