imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    
framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"         
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
#        auto_mapping: true
        default_entity_manager:   default
        entity_managers:
            default:
                connection:       default
                mappings:
                    SkNdUserBundle: ~
                    SkNdMediaBundle: ~
                    FOSUserBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport:  %mailer_transport%
    #encryption: %mailer_encryption%
    #auth_mode:  %mailer_auth_mode%
    #host:       %mailer_host%
    username:   %mailer_user%
    password:   %mailer_password%
    

jms_security_extra:
    #secure_controllers:  true
    secure_all_services: false

fos_user:
  db_driver: orm
  firewall_name: main
  user_class: SkNd\UserBundle\Entity\User
  registration:
    form:
      type: sk_nd_user_registration
    confirmation:
      from_email:
        address:        noodledig@gmail.com
        sender_name:    noodleDig Registration
  profile:
    form:
      type: sk_nd_user_profile
  resetting:
    email:
      from_email:
        address:        noodledig@gmail.com
        sender_name:    noodleDig Password reset
      
stof_doctrine_extensions:
  orm:
    default:
      sluggable: true
      timestampable: true

sk_nd_media:
  mediaapi:
    debug_mode: false
    apis: 
      amazonapi:
        access_params:
          amazon_public_key: %amazon_public_key%
          amazon_private_key: %amazon_uk_private_key%
          amazon_associate_tag: %amazon_associate_tag%
      youtubeapi: ~




#jms_aop:
#    cache_dir: %kernel.cache_dir%/jms_aop