imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
      resources: ['SkNdUserBundle:Form:fields.html.twig']

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    java:           "C:/Program Files (x86)/Java/jre6/bin/java.exe" 
    #write_to:       "%kernel.root_dir%/Resources/assets/"
    #read_from:      "%kernel.root_dir%/Resources/assets/"
    filters:
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"


# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        #auto_mapping: true
        default_entity_manager:   default
        entity_managers:
            default:
                connection:       default
                mappings:
                    SkNdUserBundle: ~
                    SkNdMediaBundle: ~
                    FOSUserBundle: ~
#        mappings:
#          sluggable: ~
#          timestampable: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
#    auth_mode: "%mailer_authmode%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
  db_driver: orm
  firewall_name: main
  user_class: SkNd\UserBundle\Entity\User
  registration:
    form:
      type: sk_nd_user_registration
    confirmation:
      enabled: true
      from_email:
        address:        noodledig@gmail.com
        sender_name:    noodleDig Registration
  profile:
    form:
      type: sk_nd_user_profile
  resetting:
    email:
      from_email:
        address:        noodledig@gmail.com
        sender_name:    noodleDig Password reset
      
stof_doctrine_extensions:
  default_locale: "%locale%"
  orm:
    default:
      sluggable: true
      timestampable: true

sk_nd_media:
  mediaapi:
    debug_mode: false
    apis: 
      amazonapi:
        access_params:
          amazon_public_key: %amazon_public_key%
          amazon_private_key: %amazon_uk_private_key%
          amazon_associate_tag: %amazon_associate_tag%
      youtubeapi: ~
