imports:
    - { resource: config_dev.yml }


framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

security:
  firewalls:
    main:
      http_basic: ~

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
    
sk_nd_media:
  mediaapi:
    debug_mode: true    
