parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     SkNd
    database_user:     sknd
    database_password: skndpass

    mailer_transport:  gmail
    mailer_encryption: ssl
    mailer_host:       smtp.gmail.com
    mailer_user:       noodledig
    mailer_password:   password

    locale:            en
    secret:            secret
    amazon_public_key: ~
    amazon_uk_private_key: pk
    amazon_us_private_key: pk
    amazon_associate_tag: at
