parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     SkNd
    database_user:     sknd
    database_password: skndpass

    mailer_transport:  gmail
    mailer_encryption: ssl
    mailer_host:       smtp.gmail.com
    mailer_user:       noodledig
    mailer_password:   password

    locale:            en
    secret: ec26480381c197a34ceed8510cf39ad44
    amazon_public_key: AKIAJVJZWBLIJ353LQ2Q
    amazon_uk_private_key: jfpvbT7g9yURYWOYPUc8C7cw489lZuSz5aM9idBn
    amazon_us_private_key: e4qR7EjP6fWVt4ks3bO/huKI+sv2Z24icGsDyXt7
    amazon_associate_tag: noodledig-21
