SkNd\UserBundle\Entity\MemoryWallMediaResource:
  type: entity
  table: null
  #id:
  #  mediaResource:
  #    associationKey: true
  #  memoryWall:
  #    associationKey: true
  fields:
    #this has been made a unique field so it can be indexed by memory wall entity
    mediaResource_id:
      type: string
    api_id:
      type: integer
      nullable: false
  manyToOne:
    mediaResource:
      targetEntity: SkNd\MediaBundle\Entity\MediaResource
      inversedBy: memoryWallMediaResources
    memoryWall:
      targetEntity: MemoryWall
      inversedBy: memoryWallMediaResources
          
  lifecycleCallbacks: {  }
