SkNd\UserBundle\Entity\MemoryWallContent:
    type: entity
    table: null
    repositoryClass: SkNd\UserBundle\Repository\MemoryWallContentRepository
    id:
      id:
        type: string
        length: 50
      memoryWall:
        associationKey: true
    fields:
        dateCreated:
          type: datetime
          gedmo:
            timestampable:
              on: create
        lastModified:
          type: datetime
          gedmo:
            timestampable:
              on: update
        comments:
          type: string
          length: 140
          nullable: true
        coords:
          type: simple_array
          nullable: true
        flaggedComments:
          type: string
          length: 255
          nullable: true
        flaggedDate:
          type: datetime
          nullable: true
        isFlagged:
          type: boolean
          nullable: true
        wallIndex:
          type: integer
          nullable: true
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
      name: discr
      type: string
      length: 255
    discriminatorMap:
      memorywallcontent: MemoryWallContent
      memorywallugc: MemoryWallUGC
      memorywallmediaresource: MemoryWallMediaResource
    manyToOne:
      memoryWall:
        targetEntity: MemoryWall
        inversedBy: memoryWallContent
      
