SkNd\UserBundle\Entity\UGC:
  type: entity
  table: null
  fields:
    thumbnailImageUrl:
      type: string
      length: 150
    originalImageUrl:
      type: string
      length: 150
  manyToOne:
    memoryWall:
      targetEntity: MemoryWall
      inversedBy: memoryWallUGC
  lifecycleCallbacks: {  }
