SkNd\UserBundle\Entity\User:
  type: entity
  table: fos_user
  id:
   id:
     type: integer
     generator: { strategy: AUTO }
  fields:
    firstname:
      type: string
      length: 80
      nullable: true
    surname:
      type: string
      length: 80
      nullable: true
    dateofbirth:
      type: date
#    email:
#      type: string
#      unique: true
#      length: 255
#    username:
#      type: string
#      unique: true
#      length: 255
      
      

          
        
     