ThinkBack\MediaBundle\Entity\API:
  type: entity
  repositoryClass: ThinkBack\MediaBundle\Repository\APIRepository
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    apiName:
      type: string
      length: '100'
    host:
      type: string
      length: 255
      nullable: true
  lifecycleCallbacks: {  }
