ThinkBack\MediaBundle\Entity\MediaResourceListingsCache:
  type: entity
  repositoryClass: ThinkBack\MediaBundle\Repository\MediaResourceRepository
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    page:
      type: integer
    keywords:
      type: string
      length: 255
    xmlData:
      type: object
    dateCreated:
      type: datetime
  oneToOne:
    mediaType:
      targetEntity: MediaType
    decade:
      targetEntity: Decade
    genre:
      targetEntity: Genre
    api:
      targetEntity: API
  lifecycleCallbacks: {  }
