ThinkBack\MediaBundle\Entity\MediaResourceListingsCache:
  type: entity
  repositoryClass: ThinkBack\MediaBundle\Repository\MediaResourceListingsCacheRepository
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    page:
      type: integer
      nullable: true
    keywords:
      type: string
      length: 255
      nullable: true
    xmlData:
      type: object
    dateCreated:
      type: datetime
  oneToOne:
    api:
      targetEntity: API
    mediaType:
      targetEntity: MediaType  
    decade:
      targetEntity: Decade
      #nullable defaults to true for these columns
    genre:
      targetEntity: Genre
  lifecycleCallbacks: {  }
