ThinkBack\MediaBundle\Entity\RecommendedItem:
  type: entity
  repositoryClass: ThinkBack\MediaBundle\Repository\RecommendedItemRepository
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    itemId:
      type: string
      length: '50'
    title:
      type: string
      length: 255
    thumbnailUrl:
      type: string
      length: 255
    userTitle:
      type: string
      length: '150'
    userDescription:
      type: string
      length: 255
    viewCount:
      type: integer
    lastUpdated:
      type: datetime
    mediaType_id:
      type: integer
  lifecycleCallbacks: {  }
  manyToOne:
    mediaType:
      targetEntity: MediaType
#    decade:
#      targetEntity: Decade
#    genre:
#      targetEntity: Genre
      
