ThinkBack\UserBundle\Entity\User:
  properties:
      firstname:
        - NotBlank: 
            message: "First name should not be blank"
            groups: [Registration, Profile] 
        - MinLength: 
            limit: 3
            groups: [Registration, Profile]
            message: "First name must have at least {{ limit }} characters"
        - MaxLength: 
            limit: 150
            groups: [Registration, Profile]
            message: "First name must have at least {{ limit }} characters"
      surname:
        - NotBlank: 
            message: "Surname should not be blank"
            groups: [Registration, Profile]
        - MinLength: 
            limit: 3
            message: "Surname must have at least {{ limit }} characters"
            groups: [Registration, Profile]
          

