indexDefault:
    pattern:  /
    defaults: { _controller: SkNdMediaBundle:Default:index }

index:
    pattern:  /index
    defaults: { _controller: SkNdMediaBundle:Default:index }
  
error:
  pattern: /error
  defaults: { _controller: SkNdMediaBundle:Default:error }

mediaSelection:
  pattern: /mediaselection
  defaults: { _controller: SkNdMediaBundle:Media:mediaSelection }
  requirements:
    _method: GET|POST

search:
  pattern: /search/{media}/{decade}/{genre}/{keywords}/{page}/{api}
  defaults:
    _controller: SkNdMediaBundle:Media:search
    decade: all-decades
    genre: all-genres
    keywords: '-'
    page: 1    
    api: amazonapi
    
mediaDetails:
  pattern: /details/{api}/{id}/{title}
  defaults:
    _controller: SkNdMediaBundle:Media:mediaDetails

youTubeRequest:
  pattern: /youtuberequest/{title}/{mrid}
  defaults:
    _controller: SkNdMediaBundle:Media:youTubeRequest
  
#setSlugs:
#  pattern: /setSlugs/{table}
#  defaults: { _controller: SkNdMediaBundle:Media:setSlugs }
#  requirements:
#    _method: GET