indexDefault:
    pattern:  /
    defaults: { _controller: SkNdMediaBundle:Default:index }

index:
    pattern:  /index
    defaults: { _controller: SkNdMediaBundle:Default:index }
  
error:
  pattern: /error
  defaults: { _controller: SkNdMediaBundle:Default:error }

mediaSelection:
  pattern: /mediaselection
  defaults: { _controller: SkNdMediaBundle:Media:mediaSelection }
  requirements:
    _method: GET|POST

search:
  pattern: /search/{media}/{decade}/{genre}/{keywords}/{page}/{apiKey}
  defaults:
    _controller: SkNdMediaBundle:Media:search
    decade: all-decades
    genre: all-genres
    keywords: '-'
    page: 1    
    apiKey: amazonapi
    
mediaDetails:
  pattern: /mediadetails/{id}/{apiKey}
  defaults:
    _controller: SkNdMediaBundle:Media:mediaDetails
    decade: all-decades
    genre: all-genres
    keywords: '-'

youTubeRequest:
  pattern: /youtuberequest/{title}/{media}/{decade}/{genre}/{keywords}
  defaults:
    _controller: SkNdMediaBundle:Media:youTubeRequest
    keywords: '-'

  
#setSlugs:
#  pattern: /setSlugs/{table}
#  defaults: { _controller: SkNdMediaBundle:Media:setSlugs }
#  requirements:
#    _method: GET