<?php

namespace SkNd\UserBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * MemoryWallContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemoryWallContentRepository extends EntityRepository
{
}
