SkNd\MediaBundle\Entity\API:
  type: entity
  repositoryClass: SkNd\MediaBundle\Repository\APIRepository
  table: api
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      length: '100'
    friendlyName:
      type: string
      length: '100'    
    host:
      type: string
      length: 255
      nullable: true
  lifecycleCallbacks: {  }
