SkNd\MediaBundle\Entity\Decade:
  type: entity
  repositoryClass: SkNd\MediaBundle\Repository\DecadeRepository
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    decadeName:
      type: integer
      gedmo:
        - sluggable
    amazonBrowseNodeId:
      type: string
      length: 10
    sevenDigitalTag:
      type: string
      length: 10
    slug:
      type: string
      length: 128
      gedmo:
        slug:
          fields:
            - decadeName
  lifecycleCallbacks: {  }

