SkNd\MediaBundle\Entity\Genre:
  type: entity
  repositoryClass: SkNd\MediaBundle\Repository\GenreRepository
  table: genre
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    genreName:
      type: string
      length: 100
      gedmo:
        - sluggable
    mediaType_id:
      type: integer
    amazonBrowseNodeId:
      type: string
      length: 10
    sevenDigitalTag:
      type: string
      length: 50
    slug:
      type: string
      length: 128
      gedmo:
        slug:
          fields:
            - genreName
  lifecycleCallbacks: {  }
  manyToOne:
    mediaType:
      targetEntity: MediaType
    
