SkNd\MediaBundle\Entity\MediaResource:
  type: entity
  repositoryClass: SkNd\MediaBundle\Repository\MediaResourceRepository
  table: null
  fields:
    id:
      type: string
      id: true
      unique: true
      generator:
        strategy: NONE
    #itemId:
    #  type: string
    #  length: '50'
    viewCount:
      type: integer
    selectedCount:
      type: integer
      nullable: true
    lastUpdated:
      type: datetime
      gedmo:
        timestampable:
          on: update
    dateCreated:
      type: datetime
      gedmo:
        timestampable:
          on: create
          
  lifecycleCallbacks: {  }
  #there are many MediaResources to 1 mediatype so MediaResource is the owning side
  #http://docs.doctrine-project.org/projects/doctrine-orm/en/2.0.x/reference/association-mapping.html
  manyToOne:
    api:
      targetEntity: API
#      orderBy:
#        id: asc
    mediaType:
      targetEntity: MediaType
    decade:
      targetEntity: Decade
    genre:
      targetEntity: Genre
  oneToOne:
    mediaResourceCache:
      targetEntity: MediaResourceCache
      cascade: ["persist", "merge", "remove"]
      orphanRemoval: true
      joinColumn:
        name: mediaResourceCache_id
        referencedColumnName: id
        onDelete: set null
  oneToMany:
    memoryWallMediaResources:
      targetEntity: SkNd\UserBundle\Entity\MemoryWallMediaResource
      mappedBy: mediaResource
      cascade: ["persist", "merge", "remove"]
      orphanRemoval: true
      #orderBy:
      #  dateCreated: desc
      
#  manyToMany:
#    memoryWalls:
#      targetEntity: SkNd\UserBundle\Entity\MemoryWall
#      mappedBy: mediaResources
#      #cascade: ["persist"]
      
