SkNd\MediaBundle\Entity\MediaResourceListingsCache:
  type: entity
  repositoryClass: SkNd\MediaBundle\Repository\MediaResourceListingsCacheRepository
  table: mediaresourcelistingscache
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    page:
      type: integer
      nullable: true
    keywords:
      type: string
      length: 255
      nullable: true
    computedKeywords:
      type: string
      length: 255
      nullable: true
    xmlData:
      type: text
    dateCreated:
      type: datetime
      gedmo:
        timestampable:
          on: create
  manyToOne:
    api:
      targetEntity: API
      nullable: false
    mediaType:
      targetEntity: MediaType
      nullable: false 
    decade:
      targetEntity: Decade
    genre:
      targetEntity: Genre
  lifecycleCallbacks: {  }
