SkNd\MediaBundle\Entity\MediaResourceCache:
  type: entity
  table: null
  fields:
    id:
      type: string
      id: true
      unique: true
      generator:
        strategy: NONE
    xmlData:
      type: text
    dateCreated:
      type: datetime
      gedmo:
        timestampable:
          on: create
          #on: update
          #on: change
          #field: xmlData
          #value: XmlData
#    dateUpdated:
#      type: datetime
#      gedmo:
#        timestampable:
#          on: update
    slug:
      type: string
      length: 255
      gedmo:
        slug:
          fields:
            - title
    title:
      type: string
      length: 255
    imageUrl:
      type: string
      length: 255
      nullable: true
  lifecycleCallbacks: {  }
