indexDefault:
    pattern:  /
    defaults: { _controller: ThinkBackMediaBundle:Default:index }

index:
    pattern:  /index
    defaults: { _controller: ThinkBackMediaBundle:Default:index }
  
error:
  pattern: /error
  defaults: { _controller: ThinkBackMediaBundle:Default:error }

#setMedia:
#  pattern: /setMedia/{mediaType}
#  defaults: { _controller: ThinkBackMediaBundle:Media:setMedia }

mediaSelection:
  pattern: /mediaSelection
  defaults: { _controller: ThinkBackMediaBundle:Media:mediaSelection }
  requirements:
    _method: GET|POST

search:
  pattern: /search/{media}/{decade}/{genre}/{page}
  defaults:
    _controller: ThinkBackMediaBundle:Media:search
    decade: all-decades
    genre: all-genres
    page: 1    

search:
  pattern: /search/{media}/{decade}/{genre}/{keywords}/{page}
  defaults:
    _controller: ThinkBackMediaBundle:Media:search
    decade: all-decades
    genre: all-genres
    keywords: null
    page: 1    
    

#mediaSearch:
#  pattern: /mediaSearch
#  defaults: { _controller: ThinkBackMediaBundle:Media:mediaSearch }
#  requirements:
#    _method: GET|POST
#
#mediaSearchResults:
#  pattern: /mediaSearchResults/{searchSlug}
#  defaults: { _controller: ThinkBackMediaBundle:Media:mediaSearchResults }  

mediaDetails:
  pattern: /mediaDetails/{media}/{decade}/{genre}/{id}
  defaults: { _controller: ThinkBackMediaBundle:Media:mediaDetails }

youTubeRequest:
  pattern: /youTubeRequest/{title}/{media}/{decade}/{genre}
  defaults: { _controller: ThinkBackMediaBundle:Media:youTubeRequest }

#flickrRequest:
#  pattern: /flickrRequest/{title}/{media}/{decade}/{genre}
#  defaults: { _controller: ThinkBackMediaBundle:Media:flickrRequest }

  
#setSlugs:
#  pattern: /setSlugs/{table}
#  defaults: { _controller: ThinkBackMediaBundle:Media:setSlugs }
#  requirements:
#    _method: GET