indexDefault:
    pattern:  /
    defaults: { _controller: ThinkBackMediaBundle:Default:index }

index:
    pattern:  /index
    defaults: { _controller: ThinkBackMediaBundle:Default:index }
  
error:
  pattern: /error
  defaults: { _controller: ThinkBackMediaBundle:Default:error }
  
mediaSelection:
  pattern: /mediaSelection
  defaults: { _controller: ThinkBackMediaBundle:Media:mediaSelection }
  requirements:
    _method: GET
  
mediaSearchResults:
  pattern: /mediaSearchResults/
  defaults: { _controller: ThinkBackMediaBundle:Media:mediaSearchResults }
  requirements:
    _method: POST
