indexDefault:
    pattern:  /
    defaults: { _controller: ThinkBackMediaBundle:Default:index }

index:
    pattern:  /index
    defaults: { _controller: ThinkBackMediaBundle:Default:index }
  
error:
  pattern: /error
  defaults: { _controller: ThinkBackMediaBundle:Default:error }
  
mediaSelection:
  pattern: /mediaSelection
  defaults: { _controller: ThinkBackMediaBundle:Media:mediaSelection }
  requirements:
    _method: GET|POST

mediaListings:
  pattern: /mediaLitsings/{decade}/{genre}
  defaults: { _controller: ThinkBackMediaBundle:Media:mediaListings }

mediaSearch:
  pattern: /mediaSearch
  defaults: { _controller: ThinkBackMediaBundle:Media:mediaSearch }
  requirements:
    _method: GET|POST

mediaSearchResults:
  pattern: /mediaSearchResults/{searchSlug}
  defaults: { _controller: ThinkBackMediaBundle:Media:mediaSearchResults }  


  
#setSlugs:
#  pattern: /setSlugs/{table}
#  defaults: { _controller: ThinkBackMediaBundle:Media:setSlugs }
#  requirements:
#    _method: GET