indexDefault:
    pattern:  /
    defaults: { _controller: ThinkBackMediaBundle:Default:index }

index:
    pattern:  /index
    defaults: { _controller: ThinkBackMediaBundle:Default:index }
  
error:
  pattern: /error
  defaults: { _controller: ThinkBackMediaBundle:Default:error }

setMedia:
  pattern: /setMedia/{mediaType}
  defaults: { _controller: ThinkBackMediaBundle:Media:setMedia }

mediaSelection:
  pattern: /mediaSelection
  defaults: { _controller: ThinkBackMediaBundle:Media:mediaSelection }
  requirements:
    _method: GET|POST

mediaListings:
  pattern: /mediaListings/{media}/{decade}/{genre}/{page}
  defaults: { _controller: ThinkBackMediaBundle:Media:mediaListings, page: 1 }

mediaSearch:
  pattern: /mediaSearch
  defaults: { _controller: ThinkBackMediaBundle:Media:mediaSearch }
  requirements:
    _method: GET|POST

mediaSearchResults:
  pattern: /mediaSearchResults/{searchSlug}
  defaults: { _controller: ThinkBackMediaBundle:Media:mediaSearchResults }  

mediaDetails:
  pattern: /mediaDetails/{id}/{title}/{media}
  defaults: { _controller: ThinkBackMediaBundle:Media:mediaDetails }

  
#setSlugs:
#  pattern: /setSlugs/{table}
#  defaults: { _controller: ThinkBackMediaBundle:Media:setSlugs }
#  requirements:
#    _method: GET