#parameters:
#  amazonapi.class: ThinkBack\MediaBundle\Resources\MediaAPI\AmazonAPI
#  amazonapi.container: container  
#
#services:
#  amazonapi:
#    class: %amazonapi.class%
#    arguments: [%?amazonapi.container%]