parameters:
#    i_spy_si_Media.example.class: ThinkBack\MediaBundle\Example

services:
#    i_spy_si_Media.example:
#        class: %i_spy_si_Media.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
