tac:
  pattern: /termsandconditions
  defaults:
    _controller: SkNdUserBundle:Default:termsAndConditions

memoryWallsPersonalIndex:
  pattern: /memorywalls/personal/index
  defaults: 
    _controller: SkNdUserBundle:MemoryWall:personalIndex
  requirements:
    _method: GET
    
#shows memory walls for a given user, shows all public\private if user is currently logged in
#or just public ones for other users
memoryWallsIndex:
  pattern: /memorywalls/{scope}/index
  defaults: 
    _controller: SkNdUserBundle:MemoryWall:index
    scope: public
  requirements:
    _method: GET

memoryWallCreate:
  pattern: /memorywall/create
  defaults: { _controller: SkNdUserBundle:MemoryWall:create }
  requirements:
    _method: GET|POST

memoryWallShow:
  pattern: /memorywall/show/{id}/{slug}/{page}
  defaults:
    _controller: SkNdUserBundle:MemoryWall:show
    page: 1
  requirements:
    _method: GET
      
memoryWallEdit:
  pattern: /memorywall/edit/{id}/{slug}
  defaults: { _controller: SkNdUserBundle:MemoryWall:edit }
  requirements:
    _method: GET|POST
      
memoryWallDelete:
  pattern: /memorywall/delete/{id}/{slug}
  defaults: { _controller: SkNdUserBundle:MemoryWall:delete }

memoryWallDeleteConfirm:
  pattern: /memorywall/delete/confirm/{id}/{slug}
  defaults: { _controller: SkNdUserBundle:MemoryWall:deleteConfirm }

memoryWallAddMediaResource:
  pattern: /memorywall/{mwid}/{slug}/add/{api}/{id}/{title}
  defaults:
    _controller: SkNdUserBundle:MemoryWallContent:addMediaResource
    slug: personal
    mwid: "-"

memoryWallDeleteMediaResource:
  pattern: /memorywall/{mwid}/{slug}/delete/{id}
  defaults:
    _controller: SkNdUserBundle:MemoryWallContent:deleteMediaResource

memoryWallDeleteMediaResourceConfirm:
  pattern: /memorywall/{mwid}/{slug}/delete/{id}/{confirmed}
  defaults:
    _controller: SkNdUserBundle:MemoryWallContent:deleteMediaResource
  requirements:
    confirmed: "true"
