memoryWallsPersonalIndex:
    pattern: /memorywalls/personal/index
    defaults: 
      _controller: SkNdUserBundle:MemoryWall:personalIndex
    requirements:
      _method: GET
    
#shows memory walls for a given user, shows all public\private if user is currently logged in
#or just public ones for other users
memoryWallsIndex:
    pattern: /memorywalls/{scope}/index
    defaults: 
      _controller: SkNdUserBundle:MemoryWall:index
      scope: public
    requirements:
      _method: GET

memoryWallCreate:
    pattern: /memorywall/create
    defaults: { _controller: SkNdUserBundle:MemoryWall:create }
    requirements:
      _method: GET|POST

memoryWallShow:
    pattern: /memorywall/show/{id}/{slug}
    defaults: { _controller: SkNdUserBundle:MemoryWall:show }
    requirements:
      _method: GET
      
memoryWallEdit:
    pattern: /memorywall/edit/{id}/{slug}
    defaults: { _controller: SkNdUserBundle:MemoryWall:edit }
    requirements:
      _method: GET