parameters:
#    i_spy_si_user.example.class: SkNd\UserBundle\Example

services:
  SkNd_user.registration.form.type:
    class: SkNd\UserBundle\Form\Type\RegistrationFormType
    arguments: [%fos_user.model.user.class%]
    tags:
      - { name: form.type, alias: sk_nd_user_registration }


#    i_spy_si_user.example:
#        class: %i_spy_si_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

